# Generated by Django 4.1.2 on 2022-10-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='alta',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='integrante',
            name='dni',
            field=models.IntegerField(default=None),
        ),
    ]
